name: Ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: pgdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Vet
        run: make vet

      - name: Test
        run: make test
        env:
          TEST_PG_DNS: postgresql://pguser:pgpass@localhost:5432/pgdb
