name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Golintci
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52

      - name: Lint
        run: make lint

      - name: Vet
        run: make vet

      - name: Test
        run: make test
